import type { Copy } from "../workspaceCopy";

export const en: Copy = {
  actionError: "The action failed.",
  loadOrganizationError: "The organisation could not be loaded.",
  decisionError: "The decision could not be saved.",
  noStaffAccess: "You do not have staff access.",
  noAdminAccess: "You do not have administrator access.",
  back: "Back",
  details: "Details",
  triage: "Client tickets",
  calendarMeetings: "Meetings",
  contactRequests: "Contact requests",
  clientPortal: "Client portal",
  logout: "Sign out",
  administration: "Administration",
  workspace: "Workspace",
  staffWorkspace: "STAFF WORKSPACE",
  administrator: "Administrator",
  adminCenter: "ADMIN CONTROL CENTER",
  new: "New",
  inProgress: "In progress",
  urgent: "Urgent",
  ticketsForWork: "Tickets to process",
  start: "Start",
  end: "End",
  assignedAdvisor: "Assigned adviser",
  choose: "Choose",
  location: "Location",
  notes: "Notes",
  confirm: "Confirm",
  reject: "Reject",
  complete: "Complete",
  publicDma: "Public DMA requests",
  organization: "Organisation",
  close: "Close",
  employees: "employees",
  activeContacts: "Active contacts",
  downloadCalendar: "Download staff calendar (.ics)",
  liveDisconnected: "",
  sendError: "The message could not be sent.",
  attachments: "Ticket attachments",
  attachmentsHelp:
    "All documents attached to this ticket by the client or the support team.",
  noAttachments: "No documents are attached to this ticket.",
  attachDocument: "Attach document",
  attachmentDownloadError: "The document could not be downloaded.",
  attachmentUploadError: "The document could not be uploaded.",
  assignment: "Assignment",
  noExpert: "No expert",
  assign: "Assign",
  begin: "Start",
  replyClient: "Public reply",
  send: "Send",
  internalNote: "Internal note",
  saveNote: "Save note",
  finalRecommendation: "Final recommendation",
  practicalRecommendation: "Practical recommendation",
  referralRecommendation: "Referral recommendation",
  resolveTicket: "Resolve ticket",
  overview: "Overview",
  organizations: "Organisations",
  subscriptions: "Subscriptions",
  contacts: "Contact requests",
  tickets: "Tickets",
  documents: "Documents",
  allTicketDocuments: "All attached documents",
  allTicketDocumentsHelp:
    "A central view of documents attached by clients and the support team.",
  noTicketDocuments: "No documents are attached",
  noTicketDocumentsHelp:
    "Documents will appear here as soon as they are attached to a ticket or contact request.",
  noContactRequests: "No contact requests",
  noContactRequestsHelp:
    "Requests submitted through the public contact form will appear here.",
  users: "Users",
  content: "Content",
  reports: "Reports",
  evidence: "Evidence documents",
  settings: "Settings",
  audit: "Audit records",
  activeSubscriptions: "Active subscriptions",
  expiredCancelled: "expired/cancelled",
  aiActRequests: "AI Act requests",
  publicInstitutions: "public institutions",
  members: "Members",
  approve: "Approve",
  suspend: "Suspend",
  reactivate: "Reactivate",
  renewSubscription: "Renew subscription",
  newInvitation: "New invitation",
  user: "User",
  sendInvitation: "Send invitation",
  reference: "Reference",
  note: "Note",
  activate: "Activate",
  confirmOfflinePayment: "Confirm offline payment",
  pendingPaymentInstruction:
    "These clients are waiting for confirmation. Enter the payment reference and select Activate.",
  paymentSettings: "Payment instructions",
  paymentSettingsHelp:
    "Enter only CRM System's official bank details. Clients with Pending payment status will see this information.",
  paymentRecipient: "Recipient",
  paymentBank: "Bank",
  paymentAccount: "Bank account",
  paymentAmount: "Amount",
  paymentCurrency: "Currency",
  paymentPurpose: "Payment purpose",
  paymentReferenceGuide: "Payment reference instructions",
  paymentSupportEmail: "Payment support email",
  savePaymentSettings: "Save payment instructions",
  cancel: "Cancel",
  validUntil: "Valid until",
  handled: "Mark as handled",
  inviteRegistration: "Invite to register",
  emailReply: "Email reply",
  adminTicketOverview: "Administrator ticket overview",
  usersRoles: "Users and roles",
  addRole: "Add role",
  deactivate: "Deactivate",
  service: "Service",
  publicPage: "Public page",
  aiHelpSubscriptions: "Customer support subscriptions",
  confirmedMeetings: "Confirmed meetings",
  referrals: "Referral recommendations",
  detailedReports: "Detailed PDF reports",
  contactsBreakdown: "Contacts",
  ticketsBreakdown: "Tickets",
  meetingsBreakdown: "Meetings",
  referralsBreakdown: "Referrals",
  exportData: "Report exports",
  downloadExcel: "Download Excel",
  downloadCsv: "Download CSV",
  groupBy: "grouped by",
  newEvidence: "New evidence record",
  relatedType: "Related type",
  relatedId: "Related ID",
  kpiCategory: "KPI category",
  period: "Period",
  template: "Template",
  file: "File",
  uploadEvidence: "Upload evidence",
  evidenceRegister: "Evidence document register",
  download: "Download",
  preview: "Preview",
  previewBlocked:
    "The preview was blocked by the browser. Allow pop-ups or download the document.",
  templateRegister: "Evidence templates",
  downloadBlank: "Download Excel template",
  selectTemplate: "Select template",
  chooseEvidenceFile: "Choose an evidence file.",
  evidenceDownloadError: "The evidence file could not be downloaded.",
  reportDownloadError: "The report could not be downloaded.",
  systemSetting: "System setting",
  key: "Key",
  value: "Value",
  description: "Description",
  save: "Save",
  systemActivities: "Append-only system activities",
  status: "Status",
  category: "Category",
  title: "Title",
  slug: "Slug",
  created: "Created",
  emailVerified: "Email verified",
  staffArea: "Staff workspace",
  onlineLink: "Online link",
  helpDeskAgent: "Help-desk agent",
  expert: "Expert",
  clientOrganization: "CLIENT ORGANISATION",
  dmaContactRequest: "DMA CONTACT REQUEST",
  primaryContact: "primary contact",
  dmaCategory: "Internal DMA category",
};
