import type { Copy } from "../workspaceCopy";

export const mk: Copy = {
  actionError: "Акцијата не успеа.",
  loadOrganizationError: "Организацијата не може да се вчита.",
  decisionError: "Одлуката не може да се зачува.",
  noStaffAccess: "Немате staff пристап.",
  noAdminAccess: "Немате администраторски пристап.",
  back: "Назад",
  details: "Детали",
  triage: "Клиентски тикети",
  calendarMeetings: "Состаноци",
  contactRequests: "Контакт барања",
  clientPortal: "Клиентски портал",
  logout: "Одјави се",
  administration: "Администрација",
  workspace: "Работен простор",
  staffWorkspace: "РАБОТЕН ПРОСТОР ЗА ПОДДРШКА",
  administrator: "Администратор",
  adminCenter: "АДМИН КОНТРОЛЕН ЦЕНТАР",
  new: "Нови",
  inProgress: "Во тек",
  urgent: "Итни",
  ticketsForWork: "Тикети за обработка",
  start: "Почеток",
  end: "Крај",
  assignedAdvisor: "Доделен советник",
  choose: "Избери",
  location: "Локација",
  notes: "Белешки",
  confirm: "Потврди",
  reject: "Одбиј",
  complete: "Заврши",
  publicDma: "Јавни DMA барања",
  organization: "Организација",
  close: "Затвори",
  employees: "вработени",
  activeContacts: "Активни контакти",
  downloadCalendar: "Преземи staff календар (.ics)",
  liveDisconnected: "",
  sendError: "Пораката не може да се испрати.",
  attachments: "Прилози од тикетот",
  attachmentsHelp:
    "Сите документи што клиентот или тимот ги прикачиле на овој тикет.",
  noAttachments: "На овој тикет нема прикачени документи.",
  attachDocument: "Прикачи документ",
  attachmentDownloadError: "Документот не може да се преземе.",
  attachmentUploadError: "Документот не може да се прикачи.",
  assignment: "Доделување",
  noExpert: "Без експерт",
  assign: "Додели",
  begin: "Започни",
  replyClient: "Јавен одговор",
  send: "Испрати",
  internalNote: "Внатрешна белешка",
  saveNote: "Зачувај белешка",
  finalRecommendation: "Финална препорака",
  practicalRecommendation: "Практична препорака",
  referralRecommendation: "Препорака за упатување",
  resolveTicket: "Реши тикет",
  overview: "Преглед",
  organizations: "Организации",
  subscriptions: "Претплати",
  contacts: "Контакт барања",
  tickets: "Тикети",
  documents: "Документи",
  allTicketDocuments: "Сите приложени документи",
  allTicketDocumentsHelp:
    "Централен преглед на документите прикачени од клиентите и тимот за поддршка.",
  noTicketDocuments: "Нема прикачени документи",
  noTicketDocumentsHelp:
    "Документите ќе се појават тука веднаш штом ќе бидат прикачени на тикет или контакт-барање.",
  noContactRequests: "Нема нови контакт барања",
  noContactRequestsHelp:
    "Овде се прикажуваат барањата испратени преку јавната контакт-форма.",
  users: "Корисници",
  content: "Содржина",
  reports: "Извештаи",
  evidence: "Доказни документи",
  settings: "Поставки",
  audit: "Ревизиски записи",
  activeSubscriptions: "Активни претплати",
  expiredCancelled: "истечени/откажани",
  aiActRequests: "AI Act барања",
  publicInstitutions: "јавни институции",
  members: "Членови",
  approve: "Одобри",
  suspend: "Суспендирај",
  reactivate: "Повторно активирај",
  renewSubscription: "Обнови претплата",
  newInvitation: "Нова покана",
  user: "Корисник",
  sendInvitation: "Испрати покана",
  reference: "Референца",
  note: "Белешка",
  activate: "Активирај",
  confirmOfflinePayment: "Потврди офлајн уплата",
  pendingPaymentInstruction:
    "Овие клиенти чекаат потврда. Внесете референца од уплатата и притиснете „Активирај“.",
  paymentSettings: "Инструкции за уплата",
  paymentSettingsHelp:
    "Внесете ги само официјалните банкарски податоци на CRM System. Клиентите со статус „Се чека уплата“ ќе ги гледаат овие информации.",
  paymentRecipient: "Примач",
  paymentBank: "Банка",
  paymentAccount: "Трансакциска сметка",
  paymentAmount: "Износ",
  paymentCurrency: "Валута",
  paymentPurpose: "Цел на дознака",
  paymentReferenceGuide: "Упатство за повикување на број / референца",
  paymentSupportEmail: "Е-пошта за помош при уплата",
  savePaymentSettings: "Зачувај инструкции за уплата",
  cancel: "Откажи",
  validUntil: "Важи до",
  handled: "Означи како обработено",
  inviteRegistration: "Покани регистрација",
  emailReply: "Одговор по е-пошта",
  adminTicketOverview: "Администраторски преглед на тикети",
  usersRoles: "Корисници и улоги",
  addRole: "Додај улога",
  deactivate: "Деактивирај",
  service: "Услуга",
  publicPage: "Јавна страница",
  aiHelpSubscriptions: "Претплати за корисничка поддршка",
  confirmedMeetings: "Потврдени состаноци",
  referrals: "Препораки за упатување",
  detailedReports: "Детални извештаи",
  contactsBreakdown: "Контакти",
  ticketsBreakdown: "Тикети",
  meetingsBreakdown: "Состаноци",
  referralsBreakdown: "Упатувања",
  exportData: "Извоз на извештаи",
  downloadExcel: "Преземи Excel",
  downloadCsv: "Преземи CSV",
  groupBy: "групирано по",
  newEvidence: "Ново доказно досие",
  relatedType: "Поврзан тип",
  relatedId: "Поврзан ID",
  kpiCategory: "KPI категорија",
  period: "Период",
  template: "Образец",
  file: "Датотека",
  uploadEvidence: "Прикачи доказ",
  evidenceRegister: "Регистар на доказни документи",
  download: "Преземи",
  preview: "Прегледај",
  previewBlocked:
    "Прегледот е блокиран од прелистувачот. Дозволете pop-up или преземете го документот.",
  templateRegister: "Обрасци за доказни документи",
  downloadBlank: "Преземи Excel образец",
  selectTemplate: "Избери образец",
  chooseEvidenceFile: "Изберете доказна датотека.",
  evidenceDownloadError: "Доказната датотека не може да се преземе.",
  reportDownloadError: "Извештајот не може да се преземе.",
  systemSetting: "Системска поставка",
  key: "Клуч",
  value: "Вредност",
  description: "Опис",
  save: "Зачувај",
  systemActivities: "Непроменливи системски активности",
  status: "Статус",
  category: "Категорија",
  title: "Наслов",
  slug: "URL ознака",
  created: "Креирано",
  emailVerified: "Е-пошта потврдена",
  staffArea: "Работен простор за поддршка",
  onlineLink: "Онлајн врска",
  helpDeskAgent: "Help-desk советник",
  expert: "Експерт",
  clientOrganization: "КЛИЕНТСКА ОРГАНИЗАЦИЈА",
  dmaContactRequest: "DMA КОНТАКТ БАРАЊЕ",
  primaryContact: "примарен контакт",
  dmaCategory: "Внатрешна DMA категорија",
};
