import type { Copy } from "../workspaceCopy";
import { en } from "./en";

export const sq: Copy = {
  ...en,
  actionError: "Veprimi dështoi.",
  loadOrganizationError: "Organizata nuk mund të ngarkohej.",
  decisionError: "Vendimi nuk mund të ruhej.",
  noStaffAccess: "Nuk keni qasje si staf.",
  noAdminAccess: "Nuk keni qasje administratori.",
  back: "Kthehu",
  details: "Detajet",
  triage: "Tiketat e klientëve",
  calendarMeetings: "Takimet",
  contactRequests: "Kërkesat e kontaktit",
  clientPortal: "Portali i klientit",
  logout: "Dilni",
  administration: "Administrimi",
  workspace: "Hapësira e punës",
  staffWorkspace: "HAPËSIRA E STAFIT",
  administrator: "Administrator",
  adminCenter: "QENDRA E KONTROLLIT ADMIN",
  new: "Të reja",
  inProgress: "Në proces",
  urgent: "Urgjente",
  ticketsForWork: "Tiketa për përpunim",
  start: "Fillimi",
  end: "Fundi",
  assignedAdvisor: "Këshilltari i caktuar",
  choose: "Zgjidh",
  location: "Vendndodhja",
  notes: "Shënime",
  confirm: "Konfirmo",
  reject: "Refuzo",
  complete: "Përfundo",
  publicDma: "Kërkesa publike DMA",
  organization: "Organizata",
  close: "Mbyll",
  employees: "punonjës",
  activeContacts: "Kontakte aktive",
  downloadCalendar: "Shkarko kalendarin e stafit (.ics)",
  liveDisconnected: "",
  sendError: "Mesazhi nuk mund të dërgohej.",
  attachments: "Dokumentet e tiketës",
  attachmentsHelp:
    "Të gjitha dokumentet e ngarkuara në këtë tiketë nga klienti ose ekipi.",
  noAttachments: "Nuk ka dokumente të ngarkuara në këtë tiketë.",
  attachDocument: "Ngarko dokument",
  attachmentDownloadError: "Dokumenti nuk mund të shkarkohej.",
  attachmentUploadError: "Dokumenti nuk mund të ngarkohej.",
  assignment: "Caktimi",
  noExpert: "Pa ekspert",
  assign: "Cakto",
  begin: "Fillo",
  replyClient: "Përgjigje publike",
  send: "Dërgo",
  internalNote: "Shënim i brendshëm",
  saveNote: "Ruaj shënimin",
  finalRecommendation: "Rekomandimi përfundimtar",
  practicalRecommendation: "Rekomandim praktik",
  referralRecommendation: "Rekomandim referimi",
  resolveTicket: "Zgjidh tiketën",
  overview: "Përmbledhje",
  organizations: "Organizatat",
  subscriptions: "Abonimet",
  contacts: "Kërkesat e kontaktit",
  tickets: "Tiketat",
  documents: "Dokumentet",
  allTicketDocuments: "Të gjitha dokumentet e bashkëngjitura",
  allTicketDocumentsHelp:
    "Pamje qendrore e dokumenteve të ngarkuara nga klientët dhe ekipi i mbështetjes.",
  noTicketDocuments: "Nuk ka dokumente të ngarkuara",
  noTicketDocumentsHelp:
    "Dokumentet do të shfaqen këtu sapo të ngarkohen në një tiketë ose kërkesë kontakti.",
  noContactRequests: "Nuk ka kërkesa kontakti",
  noContactRequestsHelp:
    "Kërkesat e dërguara përmes formularit publik do të shfaqen këtu.",
  users: "Përdoruesit",
  content: "Përmbajtja",
  reports: "Raportet",
  evidence: "Dokumentet dëshmuese",
  settings: "Cilësimet",
  audit: "Regjistrat e auditimit",
  activeSubscriptions: "Abonime aktive",
  expiredCancelled: "të skaduara/anuluara",
  aiActRequests: "kërkesa AI Act",
  publicInstitutions: "institucione publike",
  members: "Anëtarët",
  approve: "Mirato",
  suspend: "Pezullo",
  reactivate: "Riaktivizo",
  renewSubscription: "Rinovo abonimin",
  newInvitation: "Ftesë e re",
  user: "Përdoruesi",
  sendInvitation: "Dërgo ftesën",
  reference: "Referenca",
  note: "Shënim",
  activate: "Aktivizo",
  confirmOfflinePayment: "Konfirmo pagesën jashtë linje",
  pendingPaymentInstruction:
    "Këta klientë presin konfirmim. Vendosni referencën e pagesës dhe zgjidhni Aktivizo.",
  paymentSettings: "Udhëzimet e pagesës",
  paymentSettingsHelp:
    "Vendosni vetëm të dhënat zyrtare bankare të CRM System. Klientët në pritje të pagesës do t'i shohin këto informacione.",
  paymentRecipient: "Përfituesi",
  paymentBank: "Banka",
  paymentAccount: "Llogaria bankare",
  paymentAmount: "Shuma",
  paymentCurrency: "Valuta",
  paymentPurpose: "Qëllimi i pagesës",
  paymentReferenceGuide: "Udhëzimi për referencën e pagesës",
  paymentSupportEmail: "Email për ndihmë me pagesën",
  savePaymentSettings: "Ruaj udhëzimet e pagesës",
  cancel: "Anulo",
  validUntil: "Vlen deri më",
  handled: "Shëno si e përpunuar",
  inviteRegistration: "Fto për regjistrim",
  emailReply: "Përgjigje me email",
  adminTicketOverview: "Përmbledhja administrative e tiketave",
  usersRoles: "Përdoruesit dhe rolet",
  addRole: "Shto rol",
  deactivate: "Çaktivizo",
  service: "Shërbim",
  publicPage: "Faqe publike",
  aiHelpSubscriptions: "Abonime për mbështetjen e klientëve",
  confirmedMeetings: "Takime të konfirmuara",
  referrals: "Rekomandime referimi",
  detailedReports: "Raporte të detajuara",
  contactsBreakdown: "Kontaktet",
  ticketsBreakdown: "Tiketat",
  meetingsBreakdown: "Takimet",
  referralsBreakdown: "Referimet",
  exportData: "Eksporti i raporteve",
  downloadExcel: "Shkarko Excel",
  downloadCsv: "Shkarko CSV",
  groupBy: "grupuar sipas",
  newEvidence: "Dosje e re dëshmuese",
  relatedType: "Lloji i lidhur",
  relatedId: "ID e lidhur",
  kpiCategory: "Kategoria KPI",
  period: "Periudha",
  template: "Modeli",
  file: "Skedari",
  uploadEvidence: "Ngarko dëshminë",
  evidenceRegister: "Regjistri i dokumenteve dëshmuese",
  download: "Shkarko",
  preview: "Shiko",
  previewBlocked:
    "Shikimi u bllokua nga shfletuesi. Lejoni pop-up ose shkarkoni dokumentin.",
  templateRegister: "Modelet e dëshmive",
  downloadBlank: "Shkarko modelin Excel",
  selectTemplate: "Zgjidh model",
  chooseEvidenceFile: "Zgjidhni një skedar dëshmues.",
  evidenceDownloadError: "Skedari dëshmues nuk mund të shkarkohej.",
  reportDownloadError: "Raporti nuk mund të shkarkohej.",
  systemSetting: "Cilësim i sistemit",
  key: "Çelësi",
  value: "Vlera",
  description: "Përshkrimi",
  save: "Ruaj",
  systemActivities: "Aktivitete të pandryshueshme të sistemit",
  status: "Statusi",
  category: "Kategoria",
  title: "Titulli",
  slug: "Shenja URL",
  created: "Krijuar",
  emailVerified: "Email-i u verifikua",
  staffArea: "Hapësira e punës së stafit",
  onlineLink: "Lidhja online",
  helpDeskAgent: "Këshilltar i help-desk",
  expert: "Ekspert",
  clientOrganization: "ORGANIZATA KLIENTE",
  dmaContactRequest: "KËRKESË KONTAKTI DMA",
  primaryContact: "kontakt kryesor",
  dmaCategory: "Kategoria e brendshme DMA",
};
