CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AccountChangeRequests" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "RequestType" text NOT NULL,
        "Details" text NOT NULL,
        "Status" text NOT NULL,
        "DecisionNote" text,
        "DecidedBy" uuid,
        "DecidedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_AccountChangeRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "PreferredLanguage" text NOT NULL,
        "Status" text NOT NULL,
        "EmailVerifiedAt" timestamp with time zone,
        "OrganizationId" uuid,
        "LastLoginAt" timestamp with time zone,
        "TermsAcceptedAt" timestamp with time zone,
        "MustChangePassword" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AuditLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ActorUserId" uuid,
        "ActorIp" text,
        "Action" text NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" text NOT NULL,
        "OldValuesJson" text,
        "NewValuesJson" text,
        "MetadataJson" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "ContactRequestAttachments" (
        "Id" uuid NOT NULL,
        "ContactRequestId" uuid NOT NULL,
        "FileId" uuid NOT NULL,
        "UploadedBy" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactRequestAttachments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "ContactRequests" (
        "Id" uuid NOT NULL,
        "CreatedTenantId" text NOT NULL,
        "OwnerTenantId" text NOT NULL,
        "OwnershipTransferredAt" timestamp with time zone,
        "UserId" uuid,
        "RequestType" text NOT NULL,
        "OrganizationName" text NOT NULL,
        "OrganizationType" text NOT NULL,
        "Sector" text,
        "Municipality" text,
        "Region" text,
        "Website" text,
        "TaxNumber" text,
        "RegistrationNumber" text,
        "Address" text,
        "ContactName" text NOT NULL,
        "Email" text NOT NULL,
        "Phone" text,
        "PreferredLanguage" text NOT NULL,
        "EmployeeCount" integer,
        "DigitalMaturityRating" integer,
        "DmaCategory" text NOT NULL,
        "MainNeed" text NOT NULL,
        "ChallengeDescription" text NOT NULL,
        "CurrentTools" text,
        "CurrentDataSources" text,
        "UsesAi" boolean,
        "AiUseCase" text,
        "PrivacyConcerns" text,
        "InterestedInAiActGuidance" boolean NOT NULL,
        "TrainingNeeds" text,
        "DesiredTimeline" text,
        "PreferredConsultationFormat" text,
        "SelectedServices" text,
        "ServiceItemsJson" text NOT NULL,
        "BudgetRange" text,
        "InternalNote" text,
        "ConsentToContact" boolean NOT NULL,
        "PrivacyPolicyAccepted" boolean NOT NULL,
        "Status" text NOT NULL,
        "AssignedTo" uuid,
        "AssignedHelpDeskAdvisorId" uuid,
        "AssignedExpertId" uuid,
        "LinkedOrganizationId" uuid,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "ContactRequestTransfers" (
        "Id" uuid NOT NULL,
        "ContactRequestId" uuid NOT NULL,
        "FromTenantId" text NOT NULL,
        "ToTenantId" text NOT NULL,
        "Reason" text NOT NULL,
        "ServiceSnapshotJson" text NOT NULL,
        "TransferredBy" uuid NOT NULL,
        "TransferredAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactRequestTransfers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "ContentPages" (
        "Id" uuid NOT NULL,
        "Slug" text NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_ContentPages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "EvidenceFiles" (
        "Id" uuid NOT NULL,
        "RelatedEntityType" text NOT NULL,
        "RelatedEntityId" uuid NOT NULL,
        "FileId" uuid NOT NULL,
        "KpiCategory" text,
        "ReportingPeriod" text,
        "TemplateType" text,
        "CreatedBy" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_EvidenceFiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "EvidenceTemplates" (
        "Id" uuid NOT NULL,
        "Code" text NOT NULL,
        "Name" text NOT NULL,
        "RelatedEntityType" text NOT NULL,
        "Description" text NOT NULL,
        "RequiredMetadataJson" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_EvidenceTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Files" (
        "Id" uuid NOT NULL,
        "OriginalFilename" text NOT NULL,
        "StoredPath" text NOT NULL,
        "ContentType" text NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "Checksum" text NOT NULL,
        "Visibility" text NOT NULL,
        "UploadedBy" uuid NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Files" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Meetings" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "RequestedByUserId" uuid NOT NULL,
        "CreatedByUserId" uuid,
        "AssignedUserId" uuid,
        "TicketId" uuid,
        "Subject" text NOT NULL,
        "Description" text NOT NULL,
        "MeetingType" text NOT NULL,
        "Location" text,
        "OnlineLink" text,
        "RequestedTimeWindow" text,
        "StartsAt" timestamp with time zone,
        "EndsAt" timestamp with time zone,
        "Status" text NOT NULL,
        "Notes" text,
        "ConfirmedBy" uuid,
        "ConfirmedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Meetings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Notifications" (
        "Id" uuid NOT NULL,
        "RecipientUserId" uuid,
        "RecipientEmail" text,
        "Language" text,
        "Type" text NOT NULL,
        "Channel" text NOT NULL,
        "Subject" text NOT NULL,
        "Body" text NOT NULL,
        "Status" text NOT NULL,
        "SentAt" timestamp with time zone,
        "AttemptCount" integer NOT NULL,
        "NextAttemptAt" timestamp with time zone,
        "LastError" text,
        "IsRead" boolean NOT NULL,
        "ActionUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "OrganizationMembers" (
        "Id" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "MemberStatus" text NOT NULL,
        "IsPrimaryContact" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_OrganizationMembers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Organizations" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Type" text NOT NULL,
        "Sector" text,
        "Municipality" text,
        "Region" text,
        "Website" text,
        "EmployeeCount" integer,
        "Status" text NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        "ApprovedBy" uuid,
        "ApprovedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Organizations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TokenHash" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedByHash" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "ServiceCatalogueItems" (
        "Id" uuid NOT NULL,
        "Slug" text NOT NULL,
        "Status" text NOT NULL,
        "Category" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_ServiceCatalogueItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "SubscriptionInvitations" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "TokenHash" text NOT NULL,
        "Status" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "CreatedBy" uuid NOT NULL,
        "AcceptedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_SubscriptionInvitations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Subscriptions" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "InvitationId" uuid,
        "Status" text NOT NULL,
        "StartsAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone,
        "OfflinePaymentReference" text,
        "PaymentNote" text,
        "InvitedBy" uuid,
        "ActivatedBy" uuid,
        "ActivatedAt" timestamp with time zone,
        "CancelledBy" uuid,
        "CancelledAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "SystemSettings" (
        "Id" uuid NOT NULL,
        "Key" text NOT NULL,
        "Value" text NOT NULL,
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "TicketAttachments" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "MessageId" uuid,
        "FileId" uuid NOT NULL,
        "UploadedBy" uuid NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_TicketAttachments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "TicketMessages" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "SenderUserId" uuid NOT NULL,
        "MessageType" text NOT NULL,
        "Body" text NOT NULL,
        "EditedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_TicketMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Tickets" (
        "Id" uuid NOT NULL,
        "TicketNumber" text NOT NULL,
        "OrganizationId" uuid NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        "Category" text NOT NULL,
        "Priority" text NOT NULL,
        "Status" text NOT NULL,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "AssignedAgentId" uuid,
        "AssignedExpertId" uuid,
        "FinalRecommendation" text,
        "ReferralRecommendation" text,
        "ResolvedAt" timestamp with time zone,
        "ClosedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "Translations" (
        "Id" uuid NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" uuid NOT NULL,
        "Language" text NOT NULL,
        "FieldName" text NOT NULL,
        "Value" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_Translations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "UserTenantMemberships" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "AccessLevel" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "TenantId" text NOT NULL,
        CONSTRAINT "PK_UserTenantMemberships" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_AccountChangeRequests_UserId_Status" ON "AccountChangeRequests" ("UserId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_AspNetUsers_OrganizationId" ON "AspNetUsers" ("OrganizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_ContactRequestAttachments_ContactRequestId_FileId" ON "ContactRequestAttachments" ("ContactRequestId", "FileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_ContactRequests_CreatedTenantId" ON "ContactRequests" ("CreatedTenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_ContactRequests_Email" ON "ContactRequests" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_ContactRequests_OwnerTenantId" ON "ContactRequests" ("OwnerTenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_ContactRequests_UserId" ON "ContactRequests" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_ContactRequestTransfers_ContactRequestId_TransferredAt" ON "ContactRequestTransfers" ("ContactRequestId", "TransferredAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_ContentPages_TenantId_Slug" ON "ContentPages" ("TenantId", "Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_EvidenceTemplates_TenantId_Code" ON "EvidenceTemplates" ("TenantId", "Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE INDEX "IX_Files_TenantId_Id" ON "Files" ("TenantId", "Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_OrganizationMembers_OrganizationId_UserId" ON "OrganizationMembers" ("OrganizationId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_ServiceCatalogueItems_TenantId_Slug" ON "ServiceCatalogueItems" ("TenantId", "Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_SystemSettings_TenantId_Key" ON "SystemSettings" ("TenantId", "Key");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_TicketAttachments_TicketId_FileId" ON "TicketAttachments" ("TicketId", "FileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_Tickets_TenantId_TicketNumber" ON "Tickets" ("TenantId", "TicketNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_Translations_TenantId_EntityType_EntityId_Language_FieldName" ON "Translations" ("TenantId", "EntityType", "EntityId", "Language", "FieldName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    CREATE UNIQUE INDEX "IX_UserTenantMemberships_TenantId_UserId" ON "UserTenantMemberships" ("TenantId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260827173751_InitialSharedTenantSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260827173751_InitialSharedTenantSchema', '10.0.3');
    END IF;
END $EF$;
COMMIT;

