export const en = {
  help: {
    title: "From question to practical recommendation.",
    lead: "Active subscribers receive a secure ticket, real-time conversation and direct access to an adviser.",
    notice:
      "The Customer Support provides initial guidance and recommendations. It is not formal legal advice or regulatory approval.",
    access: "SUBSCRIBER ACCESS",
    login: "Sign in to the portal",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    noAccount: "No account yet?",
    register: "Create one.",
    forgot: "Forgot your password?",
    error: "Sign-in failed.",
    invalidCredentials:
      "The email address or password is incorrect. Check the details and try again.",
    serverUnavailable: "The server is not running or cannot be reached.",
    accountUnavailable:
      "This account is not allowed to sign in. Check that it has been activated.",
  },
  dma: {
    kicker: "DIGITAL MATURITY ASSESSMENT",
    title: "Tell us what you want to achieve.",
    lead: "A concise DMA assessment that helps us guide you to the right CRM System service.",
    response: "Response within 2 working days",
    support: "MK, EN and SQ support",
    consultation: "Online or in-person consultation",
    organization: "Organisation",
    name: "Name",
    type: "Type",
    sector: "Sector",
    municipality: "Municipality",
    region: "Region",
    website: "Website",
    employees: "Number of employees",
    contact: "Contact",
    fullName: "Full name",
    email: "Email",
    phone: "Phone",
    language: "Language",
    maturity: "Digital maturity and need",
    selfRating: "Self-rating 1–5",
    beginner: "Beginner",
    advanced: "Advanced",
    mainNeed: "Main need",
    ai: "Artificial intelligence",
    digitalization: "Digitalisation",
    training: "Training",
    funding: "Funding",
    other: "Other",
    challenge: "Business or public-service challenge",
    tools: "Current software/tools",
    dataSources: "Current data sources",
    usesAi: "Do you use AI?",
    no: "No",
    yes: "Yes",
    timeline: "Desired timeline",
    useCase: "AI use-case idea",
    privacyConcerns: "Privacy/compliance concerns",
    trainingNeeds: "Training needs",
    format: "Consultation format",
    noPreference: "No preference",
    online: "Online",
    inPerson: "In person",
    aiAct: "I am interested in AI Act guidance.",
    consent: "I agree to be contacted.",
    privacy: "I accept the privacy policy.",
    send: "Send request",
    received: "Request received.",
    confirmation:
      "A confirmation was sent to your email. The CRM System team will contact you.",
    newRequest: "New request",
    error: "The request could not be sent.",
  },
  training: {
    kicker: "TRAINING & SKILLS",
    title: "Knowledge for practical digital transformation.",
    lead: "The training catalogue is ready for Moodle integration. Until full SSO is connected, the CRM System team will recommend suitable training through a contact request.",
    aiTitle: "AI foundations",
    aiText:
      "An introduction to responsible and practical use of artificial intelligence.",
    dataTitle: "Data governance",
    dataText: "Data quality, privacy and governance.",
    actTitle: "AI Act",
    actText: "Initial orientation on obligations and risk management.",
    action: "Request training",
  },
  legal: {
    kicker: "LEGAL INFORMATION",
    updated:
      "Last updated: 21 July 2026. The final text must be approved by an authorised CRM System legal representative before production publication.",
    privacyTitle: "Privacy Policy",
    privacySections: [
      [
        "Data we process",
        "The portal processes account, organisation, contact request, ticket, message, meeting, uploaded document and technical audit data.",
      ],
      [
        "Why we use it",
        "Data is used to provide contracted services, user support, security, legal compliance and service improvement.",
      ],
      [
        "Access and retention",
        "Only authorised users have access according to their role. Retention and deletion periods must be defined in CRM System's official policy.",
      ],
      [
        "Your rights",
        "To request access, correction, restriction or deletion of personal data, submit a request through the contact form.",
      ],
    ],
    termsTitle: "Terms of Use",
    termsSections: [
      [
        "Portal purpose",
        "The portal provides access to CRM System services, Customer Support support, tickets, meetings and document exchange for approved organisations and active subscribers.",
      ],
      [
        "Customer Support",
        "Answers and recommendations are informational and advisory. They are not formal legal advice, certification or regulatory approval.",
      ],
      [
        "User responsibility",
        "Users must provide accurate data, protect their account and avoid uploading unlawful, malicious or unnecessarily sensitive content.",
      ],
      [
        "Availability",
        "CRM System may limit or suspend an account in case of abuse, security risk or expired subscription.",
      ],
    ],
  },
} as const;
