export const sq = {
  help: {
    title: "Nga pyetja te rekomandimi praktik.",
    lead: "Abonentët aktivë marrin tiketë të sigurt, bisedë në kohë reale dhe qasje të drejtpërdrejtë te këshilltari.",
    notice:
      "Mbështetja e klientëve ofron udhëzime dhe rekomandime fillestare. Nuk është këshillë formale juridike apo miratim rregullator.",
    access: "QASJE PËR ABONENTËT",
    login: "Hyni në portal",
    email: "Email",
    password: "Fjalëkalimi",
    submit: "Hyr",
    noAccount: "Nuk keni llogari?",
    register: "Regjistrohuni.",
    forgot: "Keni harruar fjalëkalimin?",
    error: "Hyrja dështoi.",
    invalidCredentials:
      "Email-i ose fjalëkalimi është i pasaktë. Kontrolloni të dhënat dhe provoni përsëri.",
    serverUnavailable: "Serveri nuk është aktiv ose nuk mund të arrihet.",
    accountUnavailable:
      "Kjo llogari nuk lejohet të hyjë. Kontrolloni nëse është aktivizuar.",
  },
  dma: {
    kicker: "VLERËSIMI I PJEKURISË DIGJITALE",
    title: "Na tregoni çfarë dëshironi të arrini.",
    lead: "Një vlerësim i shkurtër DMA për t'ju orientuar te shërbimi i duhur CRM System.",
    response: "Përgjigje brenda 2 ditësh pune",
    support: "Mbështetje MK, EN dhe SQ",
    consultation: "Konsultim online ose me prani",
    organization: "Organizata",
    name: "Emri",
    type: "Lloji",
    sector: "Sektori",
    municipality: "Komuna",
    region: "Rajoni",
    website: "Uebfaqja",
    employees: "Numri i punonjësve",
    contact: "Kontakti",
    fullName: "Emri dhe mbiemri",
    email: "Email",
    phone: "Telefoni",
    language: "Gjuha",
    maturity: "Pjekuria dhe nevoja digjitale",
    selfRating: "Vetëvlerësim 1–5",
    beginner: "Fillestar",
    advanced: "Avancuar",
    mainNeed: "Nevoja kryesore",
    ai: "Inteligjenca artificiale",
    digitalization: "Digjitalizimi",
    training: "Trajnimi",
    funding: "Financimi",
    other: "Tjetër",
    challenge: "Sfida e biznesit ose shërbimit publik",
    tools: "Softueri/mjetet aktuale",
    dataSources: "Burimet aktuale të të dhënave",
    usesAi: "A përdorni AI?",
    no: "Jo",
    yes: "Po",
    timeline: "Afati i dëshiruar",
    useCase: "Ide për përdorimin e AI",
    privacyConcerns: "Shqetësime për privatësi/pajtueshmëri",
    trainingNeeds: "Nevojat për trajnim",
    format: "Formati i konsultimit",
    noPreference: "Pa preferencë",
    online: "Online",
    inPerson: "Me prani",
    aiAct: "Jam i/e interesuar për udhëzime mbi AI Act.",
    consent: "Pajtohem të kontaktohem.",
    privacy: "E pranoj politikën e privatësisë.",
    send: "Dërgo kërkesën",
    received: "Kërkesa u pranua.",
    confirmation:
      "Konfirmimi u dërgua në emailin tuaj. Ekipi CRM System do t'ju kontaktojë.",
    newRequest: "Kërkesë e re",
    error: "Kërkesa nuk mund të dërgohej.",
  },
  training: {
    kicker: "TRAJNIME DHE AFTËSI",
    title: "Njohuri për transformim praktik digjital.",
    lead: "Katalogu i trajnimeve është gati për integrim me Moodle. Deri në lidhjen e plotë SSO, ekipi CRM System do të rekomandojë trajnim përmes kërkesës së kontaktit.",
    aiTitle: "Bazat e AI",
    aiText:
      "Hyrje në përdorimin e përgjegjshëm dhe praktik të inteligjencës artificiale.",
    dataTitle: "Qeverisja e të dhënave",
    dataText: "Cilësi, privatësi dhe qeverisje e të dhënave.",
    actTitle: "AI Act",
    actText: "Orientim fillestar mbi detyrimet dhe menaxhimin e rrezikut.",
    action: "Kërko trajnim",
  },
  legal: {
    kicker: "INFORMACION LIGJOR",
    updated:
      "Përditësuar më 21 korrik 2026. Teksti përfundimtar duhet të miratohet nga një përfaqësues ligjor i autorizuar i CRM System para publikimit.",
    privacyTitle: "Politika e Privatësisë",
    privacySections: [
      [
        "Të dhënat që përpunojmë",
        "Portali përpunon të dhëna të llogarisë, organizatës, kërkesave të kontaktit, tiketave, mesazheve, takimeve, dokumenteve dhe auditimit teknik.",
      ],
      [
        "Pse i përdorim",
        "Të dhënat përdoren për shërbime, mbështetje, siguri, detyrime ligjore dhe përmirësim të shërbimit.",
      ],
      [
        "Qasja dhe ruajtja",
        "Qasje kanë vetëm përdoruesit e autorizuar sipas rolit. Afatet e ruajtjes dhe fshirjes përcaktohen në politikën zyrtare të CRM System.",
      ],
      [
        "Të drejtat tuaja",
        "Për qasje, korrigjim, kufizim ose fshirje të të dhënave, dërgoni kërkesë përmes formularit të kontaktit.",
      ],
    ],
    termsTitle: "Kushtet e Përdorimit",
    termsSections: [
      [
        "Qëllimi i portalit",
        "Portali jep qasje në shërbimet CRM System, Mbështetja e klientëve, tiketa, takime dhe dokumente për organizata të miratuara dhe abonentë aktivë.",
      ],
      [
        "Mbështetja e klientëve",
        "Përgjigjet janë informative dhe këshilluese. Ato nuk janë këshillë formale juridike, certifikim apo miratim rregullator.",
      ],
      [
        "Përgjegjësia e përdoruesit",
        "Përdoruesi duhet të japë të dhëna të sakta, të mbrojë llogarinë dhe të mos ngarkojë përmbajtje të paligjshme, keqdashëse ose tepër të ndjeshme.",
      ],
      [
        "Disponueshmëria",
        "CRM System mund të kufizojë ose pezullojë llogarinë në rast abuzimi, rreziku sigurie ose abonimi të skaduar.",
      ],
    ],
  },
} as const;
